#!/usr/local/bin/bash

# function to count number of given args

# function countargs {
#     echo "$#"
# }
#
# countargs "$@"
# countargs "$*"

# echo -e ${PATH//:/'\n'}

# argument=$1
# underarg=${argument:=hello}

# echo ${argument}
# echo ${underarg:?'underarg is not assigned'}

# unset argument
# unset underarg
